<?php
	class TViewportEvents{
		public static $name=array(
			'activate'          =>'function(component,options){%CODE%}',
			'add'               =>'function(container,component,index,options){%CODE%}',
			'added'             =>'function(component,container,pos,options){%CODE%}',
			'afterlayout'       =>'function(container,layout,options){%CODE%}',
			'afterrender'       =>'function(component,options){%CODE%}',
			'beforeactivate'    =>'function(component,options){%CODE%}',
			'beforeadd'         =>'function(container,component,index,options){%CODE%}',
			'beforecardswitch'  =>'function(container,newcard,oldcard,index,animated,options){%CODE%}',
			'beforedeactivate'  =>'function(component,options){%CODE%}',
			'beforedestroy'     =>'function(component,options){%CODE%}',
			'beforehide'        =>'function(component,options){%CODE%}',
			'beforeremove'      =>'function(container,component,options){%CODE%}',
			'beforerender'      =>'function(component,options){%CODE%}',
			'beforeshow'        =>'function(component,options){%CODE%}',
			'cardswitch'        =>'function(container,newcard,oldcard,index,animated,options){%CODE%}',
			'deactivate'        =>'function(component,options){%CODE%}',
			'destroy'           =>'function(component,options){%CODE%}',
			'disable'           =>'function(component,options){%CODE%}',
			'enable'            =>'function(component,options){%CODE%}',
			'hide'              =>'function(component,options){%CODE%}',
			'move'              =>'function(component,x,y,options){%CODE%}',
			'remove'            =>'function(container,component,options){%CODE%}',
			'removed'           =>'function(component,container,options){%CODE%}',
			'render'            =>'function(component,options){%CODE%}',
			'resize'            =>'function(component,adjWidth,adjHeight,options){%CODE%}',
			'show'              =>'function(component,options){%CODE%}'
		);
	}
	class TWindowEvents{
		public static $name=array(
			'activate'          =>'function(self,options){%CODE%}',
			'add'               =>'function(container,component,index,options){%CODE%}',
			'added'             =>'function(component,container,pos,options){%CODE%}',
			'afterlayout'       =>'function(container,layout,options){%CODE%}',
			'afterrender'       =>'function(component,options){%CODE%}',
			'beforeactivate'    =>'function(component,options){%CODE%}',
			'beforeadd'         =>'function(container,component,index,options){%CODE%}',
			'beforecardswitch'  =>'function(container,newcard,oldcard,index,animated,options){%CODE%}',
			'beforecollapse'    =>'function(container,direction,animate,options){%CODE%}',
			'beforedeactivate'  =>'function(component,options){%CODE%}',
			'beforedestroy'     =>'function(component,options){%CODE%}',
			'beforeexpand'      =>'function(container,animate,options){%CODE%}',
			'beforehide'        =>'function(component,options){%CODE%}',
			'beforeremove'      =>'function(container,component,options){%CODE%}',
			'beforerender'      =>'function(component,options){%CODE%}',
			'beforeshow'        =>'function(component,options){%CODE%}',
			'cardswitch'        =>'function(container,newcard,oldcard,index,animated,options){%CODE%}',
			'collapse'          =>'function(container,options){%CODE%}',
			'deactivate'        =>'function(self,options){%CODE%}',
			'destroy'           =>'function(component,options){%CODE%}',
			'disable'           =>'function(component,options){%CODE%}',
			'enable'            =>'function(component,options){%CODE%}',
			'expand'            =>'function(container,options){%CODE%}',
			'hide'              =>'function(component,options){%CODE%}',
			'maximize'          =>'function(self,options){%CODE%}',
			'minimize'          =>'function(self,options){%CODE%}',
			'move'              =>'function(component,x,y,options){%CODE%}',
			'remove'            =>'function(container,component,options){%CODE%}',
			'removed'           =>'function(component,container,options){%CODE%}',
			'render'            =>'function(component,options){%CODE%}',
			'resize'            =>'function(self,width,height,options){%CODE%}',
			'restore'           =>'function(self,options){%CODE%}',
			'show'              =>'function(component,options){%CODE%}'
		);
	}

	class TComponentEvents{
		public static $name=array(
			'activate'   		=>'function(component,options){%CODE%}',
			'add'               =>'function(container,component,index,options){%CODE%}',
			'added'             =>'function(component,container,pos,options){%CODE%}',
			'afterlayout'       =>'function(container,layout,options){%CODE%}',
			'afterrender'       =>'function(component,options){%CODE%}',
			'beforeactivate'    =>'function(component,options){%CODE%}',
			'beforeadd'         =>'function(container,component,index,options){%CODE%}',
			'beforecardswitch'  =>'function(container,newcard,oldcard,index,animated,options){%CODE%}',
			'beforecollapse'    =>'function(container,direction,animate,options){%CODE%}',
			'beforedeactivate'  =>'function(component,options){%CODE%}',
			'beforedestroy'     =>'function(component,options){%CODE%}',
			'beforeexpand'      =>'function(container,animate,options){%CODE%}',
			'beforehide'        =>'function(component,options){%CODE%}',
			'beforepush'        =>'function(htmlEditor,html,options){%CODE%}',
			'beforeremove'      =>'function(container,component,options){%CODE%}',
			'beforerender'      =>'function(component,options){%CODE%}',
			'beforeshow'        =>'function(component,options){%CODE%}',
			'change'  		    =>'function(component,newValue,oldValue,options){%CODE%}',
			'checkchange'       =>'function(component,checked,options){%CODE%}',
			'click'             =>'function(component,eventObj,options){%CODE%}',
			'cardswitch'        =>'function(container,newcard,oldcard,index,animated,options){%CODE%}',
			'collapse'          =>'function(container,options){%CODE%}',
			'deactivate'        =>'function(self,options){%CODE%}',
			'destroy'           =>'function(component,options){%CODE%}',
			'disable'           =>'function(component,options){%CODE%}',
			'editmodechange'    =>'function(htmlEditor,sourceEdit,options){%CODE%}',
			'enable'            =>'function(component,options){%CODE%}',
			'expand'            =>'function(container,options){%CODE%}',
			'focus'             =>'function(component,options){%CODE%}',
			'hide'              =>'function(component,options){%CODE%}',
			'initialize'        =>'function(htmlEditor,options){%CODE%}',
			'maximize'          =>'function(self,options){%CODE%}',
			'minimize'          =>'function(self,options){%CODE%}',
			'move'              =>'function(component,x,y,options){%CODE%}',
			'push'              =>'function(htmlEditor,html,options){%CODE%}',
			'remove'            =>'function(container,component,options){%CODE%}',
			'removed'           =>'function(component,container,options){%CODE%}',
			'render'            =>'function(component,options){%CODE%}',
			'resize'            =>'function(self,adjWidth,adjHeight,options){%CODE%}',
			'select'            =>'function(component,value,options){%CODE%}',
			'show'              =>'function(component,options){%CODE%}',
			'sync'              =>'function(htmlEditor,isValid,options){%CODE%}',
			'validitychange'    =>'function(field,isValid,options){%CODE%}'
		);
	}
?>